-- ============================================================
-- Domain Knowledge Test Platform — Question Seed Data
-- 50 procedural/applied questions per domain (250 total)
-- Run AFTER schema.sql
-- ============================================================

INSERT INTO questions (domain, question, option_a, option_b, option_c, option_d, correct_answer) VALUES

-- ============================================================
-- DOMAIN: ai (Artificial Intelligence & Generative AI)
-- ============================================================
('ai', 'Which parameter in the OpenAI Chat Completions API controls the randomness of the output?', 'top_p', 'temperature', 'max_tokens', 'frequency_penalty', 'B'),
('ai', 'Which OpenAI API endpoint do you call to generate text embeddings?', '/v1/completions', '/v1/chat/completions', '/v1/embeddings', '/v1/fine_tuning/jobs', 'C'),
('ai', 'In the Gemini API, which Python method streams responses token by token?', 'model.generate_content(stream=True)', 'model.stream_content()', 'model.generate_stream()', 'model.run(stream=True)', 'A'),
('ai', 'Which Claude API parameter sets the persona and context for the model before the conversation starts?', 'context', 'preamble', 'system', 'instructions', 'C'),
('ai', 'In LangChain, which class wraps an OpenAI model for use in a chain?', 'OpenAI()', 'ChatOpenAI()', 'LLMChain()', 'OpenAIWrapper()', 'B'),
('ai', 'What does setting temperature=0 do in most LLM APIs?', 'Makes the model refuse all requests', 'Makes output fully deterministic and repetitive', 'Disables the model', 'Sets response length to zero', 'B'),
('ai', 'Which Gemini API parameter limits the number of candidate responses returned?', 'max_output_tokens', 'candidate_count', 'top_k', 'response_limit', 'B'),
('ai', 'In OpenAI function calling, what field in the API response tells you the model wants to call a function?', 'tool_call', 'finish_reason = "function_call"', 'function_requested', 'action_required', 'B'),
('ai', 'Which Python library do you use to load and query a FAISS vector index?', 'chromadb', 'pinecone', 'faiss', 'weaviate', 'C'),
('ai', 'In a RAG pipeline, what does the "retrieval" step return to feed into the LLM?', 'The user query rephrased', 'Relevant document chunks from a vector store', 'A summary of the entire document', 'The LLM''s previous response', 'B'),
('ai', 'Which OpenAI model parameter prevents the model from repeating the same phrases too often?', 'temperature', 'presence_penalty', 'frequency_penalty', 'top_p', 'C'),
('ai', 'What is the correct way to pass a conversation history to the OpenAI Chat Completions API?', 'history=[...]', 'messages=[{"role": "user", "content": "..."}, ...]', 'context=[...]', 'chat=[...]', 'B'),
('ai', 'In the Hugging Face Transformers library, which function loads a pre-trained model and tokenizer together?', 'pipeline()', 'AutoModel.from_pretrained()', 'load_model()', 'Trainer()', 'A'),
('ai', 'Which command installs the official Anthropic Python SDK?', 'pip install claude', 'pip install anthropic', 'pip install claude-sdk', 'pip install anthropic-ai', 'B'),
('ai', 'In LangChain, which component stores conversation history and passes it automatically to the LLM?', 'ConversationChain', 'Memory', 'ConversationBufferMemory', 'HistoryChain', 'C'),
('ai', 'What does top_p=0.1 do in an LLM API call?', 'Limits response to 10% of max tokens', 'Restricts sampling to the top 10% probability mass (more focused output)', 'Sets response quality to 10%', 'Reduces temperature by 10%', 'B'),
('ai', 'Which Gemini API safety setting category blocks harmful or dangerous content?', 'HARM_CATEGORY_DANGEROUS_CONTENT', 'HARM_CATEGORY_VIOLENCE', 'HARM_CATEGORY_UNSAFE', 'HARM_CATEGORY_BLOCKED', 'A'),
('ai', 'In OpenAI''s API, what role label is used for the AI''s previous responses in a chat history array?', 'bot', 'model', 'assistant', 'ai', 'C'),
('ai', 'Which method in the Anthropic SDK sends a message and waits for the full response?', 'client.messages.stream()', 'client.messages.create()', 'client.chat.send()', 'client.complete()', 'B'),
('ai', 'What is the purpose of the `stop` parameter in the OpenAI Completions API?', 'Stops the API server', 'Defines token sequences that cause generation to stop', 'Sets a timeout for the request', 'Prevents streaming', 'B'),
('ai', 'In LangChain, which class is used to create a prompt with input variables?', 'Prompt()', 'PromptTemplate()', 'ChatPrompt()', 'TemplatePrompt()', 'B'),
('ai', 'Which Gemini API method is used to count tokens in a prompt before sending it?', 'model.count_tokens()', 'model.estimate_tokens()', 'model.token_count()', 'model.preview_tokens()', 'A'),
('ai', 'What does few-shot prompting mean in practice?', 'Using a smaller model', 'Including example input-output pairs in the prompt to guide the model', 'Sending multiple API requests in parallel', 'Using less than 100 tokens', 'B'),
('ai', 'In the OpenAI API, which field specifies the model to use (e.g., "gpt-4o")?', 'engine', 'model', 'llm', 'version', 'B'),
('ai', 'Which vector database is fully managed and accessed via a Python client with upsert() and query() methods?', 'FAISS', 'ChromaDB', 'Pinecone', 'Weaviate', 'C'),
('ai', 'What does the `max_tokens` parameter control in an LLM API call?', 'The maximum number of input tokens allowed', 'The maximum number of tokens the model can generate in the response', 'The total context window size', 'The number of API retries', 'B'),
('ai', 'In LangChain, which class chains an LLM with a prompt template and runs them together?', 'Pipeline()', 'LLMChain()', 'ChainRunner()', 'ModelPipeline()', 'B'),
('ai', 'Which OpenAI API feature allows the model to call external functions defined by the developer?', 'plugins', 'tools / function_calling', 'extensions', 'actions', 'B'),
('ai', 'What Python package provides the `SentenceTransformer` class for generating text embeddings locally?', 'transformers', 'sentence-transformers', 'embedding-lib', 'openai', 'B'),
('ai', 'In the Gemini API, which parameter controls the diversity of the output by limiting the number of top tokens considered?', 'temperature', 'top_p', 'top_k', 'candidate_count', 'C'),
('ai', 'Which format does the OpenAI API use to return structured outputs when JSON mode is enabled?', 'XML', 'YAML', 'JSON', 'CSV', 'C'),
('ai', 'What does the `role: "system"` message do in an OpenAI chat request?', 'Authenticates the request', 'Sets the AI''s behavior and persona for the conversation', 'Specifies the model version', 'Enables function calling', 'B'),
('ai', 'In ChromaDB, which method adds documents and their embeddings to a collection?', 'collection.insert()', 'collection.add()', 'collection.upsert()', 'collection.push()', 'B'),
('ai', 'Which command initializes a new LangChain project with the recommended folder structure?', 'langchain init', 'langchain new', 'langchain create', 'There is no official init command', 'D'),
('ai', 'What is the purpose of `logprobs` parameter in the OpenAI API?', 'Logs API errors', 'Returns the log probabilities of output tokens', 'Enables verbose logging', 'Logs request metadata', 'B'),
('ai', 'In Hugging Face, which method runs inference on a text-generation pipeline?', 'pipeline.run()', 'pipeline(text)', 'pipeline.generate()', 'pipeline.predict()', 'B'),
('ai', 'Which Gemini API class is used to start a multi-turn chat session?', 'model.ChatSession()', 'model.start_chat()', 'model.create_chat()', 'ChatClient(model)', 'B'),
('ai', 'What does `stream=True` do in an OpenAI API call?', 'Enables WebSocket connection', 'Returns response as server-sent events token by token', 'Streams audio output', 'Increases speed by parallelizing requests', 'B'),
('ai', 'In OpenAI''s Assistants API, what is a "thread"?', 'A background task', 'A persistent conversation context with message history', 'A model fine-tuning job', 'An API rate limit bucket', 'B'),
('ai', 'Which Python library provides `AgentExecutor` for building LLM agents with tools?', 'openai', 'anthropic', 'langchain', 'huggingface_hub', 'C'),
('ai', 'What is the correct Gemini API call to generate content with a text prompt?', 'model.run("prompt")', 'model.generate_content("prompt")', 'model.complete("prompt")', 'model.predict("prompt")', 'B'),
('ai', 'In OpenAI fine-tuning, what file format must training data be in?', 'CSV', 'JSON', 'JSONL', 'XML', 'C'),
('ai', 'Which parameter in the Anthropic Claude API sets the maximum response length?', 'max_length', 'max_tokens', 'token_limit', 'output_limit', 'B'),
('ai', 'What does "grounding" do in the Gemini API?', 'Prevents hallucination by connecting model output to real-time Google Search results', 'Limits the model to factual topics only', 'Adds citations automatically', 'Reduces token usage', 'A'),
('ai', 'In LangChain, which retriever method fetches the most relevant documents for a query?', 'retriever.get()', 'retriever.fetch()', 'retriever.get_relevant_documents()', 'retriever.search()', 'C'),
('ai', 'Which Hugging Face method downloads and caches a model from the Hub?', 'hf_hub_download()', 'AutoModel.from_pretrained()', 'load_from_hub()', 'ModelHub.get()', 'B'),
('ai', 'What does setting `presence_penalty=2.0` do in an OpenAI API call?', 'Doubles response length', 'Strongly discourages the model from repeating any topic already mentioned', 'Blocks unsafe content', 'Increases creativity', 'B'),
('ai', 'In the context of LLMs, what is "context window"?', 'The UI window showing the chat', 'The maximum number of tokens (input + output) the model can process in one request', 'The cache size on the server', 'The number of few-shot examples allowed', 'B'),
('ai', 'Which OpenAI API object type is used to run an assistant on a thread?', 'Job', 'Run', 'Task', 'Execution', 'B'),
('ai', 'In LangChain, which tool allows an agent to search the web using DuckDuckGo?', 'WebSearchTool()', 'DuckDuckGoSearchRun()', 'SearchTool()', 'BrowseTool()', 'B'),

-- ============================================================
-- DOMAIN: cloud (Cloud Computing — AWS, Azure, GCP)
-- ============================================================
('cloud', 'Which AWS CLI command creates a new S3 bucket named "my-bucket" in us-east-1?', 'aws s3 create-bucket --bucket my-bucket', 'aws s3api create-bucket --bucket my-bucket --region us-east-1', 'aws s3 mb s3://my-bucket --region us-east-1', 'aws bucket create --name my-bucket', 'C'),
('cloud', 'Which AWS CLI command lists all objects in an S3 bucket?', 'aws s3 ls s3://my-bucket --recursive', 'aws s3 list --bucket my-bucket', 'aws s3api list-objects --bucket my-bucket', 'aws s3 objects --bucket my-bucket', 'A'),
('cloud', 'Which command copies a local file to an S3 bucket using the AWS CLI?', 'aws s3 put file.txt s3://my-bucket/', 'aws s3 upload file.txt s3://my-bucket/', 'aws s3 cp file.txt s3://my-bucket/', 'aws s3api put-object --bucket my-bucket --key file.txt', 'C'),
('cloud', 'What does the AWS CLI command `aws ec2 describe-instances` return?', 'Starts new EC2 instances', 'Returns metadata about existing EC2 instances', 'Lists available AMIs', 'Describes EC2 pricing', 'B'),
('cloud', 'Which AWS CLI command deploys a Lambda function from a zip file?', 'aws lambda deploy', 'aws lambda update-function-code --function-name myFn --zip-file fileb://fn.zip', 'aws lambda upload --name myFn --file fn.zip', 'aws lambda publish --zip fn.zip', 'B'),
('cloud', 'Which AWS service provides a managed Kubernetes control plane?', 'ECS', 'EKS', 'ECR', 'Fargate', 'B'),
('cloud', 'What does `aws sts get-caller-identity` return?', 'Lists IAM roles', 'Returns the AWS account ID, user ID, and ARN of the current credentials', 'Gets the current region', 'Returns active sessions', 'B'),
('cloud', 'Which AWS CLI command creates a new IAM user?', 'aws iam add-user --name myuser', 'aws iam create-user --user-name myuser', 'aws iam new --user myuser', 'aws user create --name myuser', 'B'),
('cloud', 'In AWS, which service is used to store and retrieve Docker container images?', 'S3', 'ECS', 'ECR', 'EKS', 'C'),
('cloud', 'Which Terraform command initializes a working directory and downloads providers?', 'terraform start', 'terraform setup', 'terraform init', 'terraform prepare', 'C'),
('cloud', 'Which Terraform command shows what changes will be made without applying them?', 'terraform check', 'terraform diff', 'terraform plan', 'terraform preview', 'C'),
('cloud', 'What does `terraform apply` do?', 'Validates the Terraform syntax', 'Creates, updates, or destroys infrastructure to match the configuration', 'Initializes providers', 'Generates a plan file', 'B'),
('cloud', 'Which AWS CLI command attaches an IAM policy to a user?', 'aws iam add-policy --user myuser --policy arn:...', 'aws iam attach-user-policy --user-name myuser --policy-arn arn:...', 'aws iam assign-policy --user myuser', 'aws iam grant --user myuser --policy arn:...', 'B'),
('cloud', 'Which AWS service automatically distributes incoming traffic across multiple EC2 instances?', 'Route 53', 'CloudFront', 'Elastic Load Balancer', 'Auto Scaling', 'C'),
('cloud', 'What does `aws configure` do?', 'Creates a new AWS account', 'Sets up AWS CLI credentials, region, and output format', 'Configures an EC2 instance', 'Enables MFA', 'B'),
('cloud', 'In Azure, which CLI command logs you in to your Azure account?', 'azure login', 'az auth login', 'az login', 'az account login', 'C'),
('cloud', 'Which Azure CLI command lists all resource groups in your subscription?', 'az resource list', 'az group list', 'az rg list', 'az resourcegroup show', 'B'),
('cloud', 'Which GCP CLI command sets the active project?', 'gcloud project set PROJECT_ID', 'gcloud config set project PROJECT_ID', 'gcloud use project PROJECT_ID', 'gcloud activate PROJECT_ID', 'B'),
('cloud', 'Which GCP service is equivalent to AWS Lambda?', 'Cloud Run', 'App Engine', 'Cloud Functions', 'Compute Engine', 'C'),
('cloud', 'What does `aws cloudformation create-stack` do?', 'Creates an EC2 instance', 'Deploys AWS resources defined in a CloudFormation template', 'Creates an S3 bucket', 'Provisions a VPC', 'B'),
('cloud', 'Which AWS CLI command invokes a Lambda function synchronously?', 'aws lambda run --name myFn', 'aws lambda invoke --function-name myFn output.json', 'aws lambda call --name myFn', 'aws lambda execute --name myFn', 'B'),
('cloud', 'What is the purpose of an AWS IAM Role?', 'To store encryption keys', 'To grant permissions to AWS services or users without sharing credentials', 'To create VPCs', 'To monitor resource usage', 'B'),
('cloud', 'Which AWS CLI command enables versioning on an S3 bucket?', 'aws s3 versioning enable --bucket my-bucket', 'aws s3api put-bucket-versioning --bucket my-bucket --versioning-configuration Status=Enabled', 'aws s3 version --bucket my-bucket --enable', 'aws s3api enable-versioning --bucket my-bucket', 'B'),
('cloud', 'In GCP, which CLI command deploys a Cloud Function from local source code?', 'gcloud run deploy', 'gcloud functions deploy myFn --runtime python39 --trigger-http', 'gcloud deploy function --name myFn', 'gcloud function create --name myFn', 'B'),
('cloud', 'Which AWS service provides a fully managed relational database?', 'DynamoDB', 'ElastiCache', 'RDS', 'Redshift', 'C'),
('cloud', 'What does `aws eks update-kubeconfig --name my-cluster` do?', 'Creates a new EKS cluster', 'Updates your local kubeconfig file to connect kubectl to the EKS cluster', 'Scales the EKS cluster', 'Updates the EKS cluster version', 'B'),
('cloud', 'Which Azure CLI command creates a new resource group?', 'az group new --name myRG --location eastus', 'az resourcegroup create --name myRG', 'az group create --name myRG --location eastus', 'az rg add --name myRG', 'C'),
('cloud', 'What is an AWS Security Group?', 'An IAM group with security policies', 'A virtual firewall that controls inbound and outbound traffic for EC2 instances', 'An encryption key manager', 'A VPN configuration', 'B'),
('cloud', 'Which command in the AWS CLI syncs a local folder to an S3 bucket?', 'aws s3 sync ./folder s3://my-bucket', 'aws s3 upload --folder ./folder s3://my-bucket', 'aws s3 push ./folder s3://my-bucket', 'aws s3 cp ./folder s3://my-bucket --recursive', 'A'),
('cloud', 'In AWS, what does a NAT Gateway do?', 'Translates domain names to IPs', 'Allows private subnet instances to initiate outbound internet connections', 'Balances load across instances', 'Provides direct Connect to on-premises', 'B'),
('cloud', 'Which Terraform resource block creates an AWS S3 bucket?', 'resource "aws_s3" "bucket" {}', 'resource "aws_s3_bucket" "my_bucket" {}', 'resource "s3_bucket" "my_bucket" {}', 'aws_resource "s3" "bucket" {}', 'B'),
('cloud', 'What does `aws logs tail /aws/lambda/myFn --follow` do?', 'Downloads Lambda logs to a file', 'Streams live CloudWatch log output from the Lambda function', 'Lists all Lambda log groups', 'Tails the Lambda execution role logs', 'B'),
('cloud', 'In GCP, which service is equivalent to AWS S3 for object storage?', 'Cloud SQL', 'BigQuery', 'Cloud Storage', 'Cloud Filestore', 'C'),
('cloud', 'Which AWS CLI command starts a stopped EC2 instance?', 'aws ec2 run --instance-id i-1234567890', 'aws ec2 start-instances --instance-ids i-1234567890', 'aws ec2 boot --instance-id i-1234567890', 'aws ec2 launch --instance-id i-1234567890', 'B'),
('cloud', 'What is the purpose of AWS CloudTrail?', 'Monitors application performance', 'Records all AWS API calls for auditing and compliance', 'Manages DNS records', 'Distributes content globally', 'B'),
('cloud', 'Which Azure service is equivalent to AWS Lambda?', 'Azure App Service', 'Azure Functions', 'Azure Logic Apps', 'Azure Container Instances', 'B'),
('cloud', 'Which command lists all available AWS regions using the CLI?', 'aws regions list', 'aws ec2 describe-regions', 'aws config list-regions', 'aws account list-regions', 'B'),
('cloud', 'In Terraform, what file stores the current state of deployed infrastructure?', 'terraform.plan', 'main.tf', 'terraform.tfstate', 'variables.tf', 'C'),
('cloud', 'Which AWS service provides serverless container execution without managing EC2 instances?', 'EKS', 'ECR', 'ECS with EC2', 'AWS Fargate', 'D'),
('cloud', 'What does `aws s3 presign s3://bucket/file.txt` generate?', 'A permanent public URL for the file', 'A temporary pre-signed URL for accessing the private S3 object', 'An encrypted copy of the file', 'A CloudFront distribution URL', 'B'),
('cloud', 'Which GCP CLI command lists all running Compute Engine instances?', 'gcloud compute instances list', 'gcloud vm list', 'gcloud instances show', 'gcloud compute list-vms', 'A'),
('cloud', 'What does an AWS Auto Scaling Group do?', 'Automatically upgrades EC2 instance types', 'Automatically adds or removes EC2 instances based on demand', 'Scales S3 storage capacity', 'Manages IAM permissions automatically', 'B'),
('cloud', 'Which AWS CLI flag outputs results in JSON format?', '--format json', '--output json', '--type json', '--render json', 'B'),
('cloud', 'In AWS, what is the difference between an S3 bucket policy and an ACL?', 'There is no difference', 'Bucket policies are JSON-based resource policies; ACLs are legacy per-object access controls', 'ACLs support more complex rules than bucket policies', 'Bucket policies apply per-object; ACLs apply per-bucket', 'B'),
('cloud', 'Which Azure CLI command deploys a container from Docker Hub to Azure Container Instances?', 'az container run --image nginx', 'az aci create --image nginx', 'az container create --resource-group myRG --name myContainer --image nginx --ports 80', 'az deploy container --image nginx', 'C'),
('cloud', 'What does `terraform destroy` do?', 'Removes only unused resources', 'Destroys all infrastructure managed by the current Terraform configuration', 'Resets the Terraform state file', 'Removes provider plugins', 'B'),
('cloud', 'Which AWS service is used to manage secrets and API keys securely?', 'IAM', 'KMS', 'AWS Secrets Manager', 'Parameter Store', 'C'),
('cloud', 'In GCP, which CLI command creates a new Cloud Storage bucket?', 'gcloud storage create gs://my-bucket', 'gsutil mb gs://my-bucket', 'gcloud bucket create my-bucket', 'gcloud storage mb my-bucket', 'B'),
('cloud', 'Which AWS CLI command creates a CloudWatch alarm that triggers when CPU exceeds 80%?', 'aws cloudwatch set-alarm --metric CPUUtilization --threshold 80', 'aws cloudwatch put-metric-alarm --alarm-name high-cpu --metric-name CPUUtilization --threshold 80 --comparison-operator GreaterThanThreshold --evaluation-periods 1 --period 300 --statistic Average --namespace AWS/EC2', 'aws ec2 alarm create --cpu 80', 'aws monitoring create-alarm --cpu-limit 80', 'B'),

-- ============================================================
-- DOMAIN: cybersecurity
-- ============================================================
('cybersecurity', 'What does `nmap -sV 192.168.1.1` do?', 'Scans for open ports only', 'Detects service versions running on open ports of the target', 'Runs a vulnerability scan', 'Performs a SYN flood attack', 'B'),
('cybersecurity', 'Which nmap flag performs a stealthy SYN scan without completing the TCP handshake?', '-sT', '-sU', '-sS', '-sA', 'C'),
('cybersecurity', 'What does `nmap -O` do?', 'Lists open ports in order', 'Attempts to detect the operating system of the target', 'Outputs results to a file', 'Runs an OSINT scan', 'B'),
('cybersecurity', 'Which Metasploit command searches for exploit modules by keyword?', 'find exploit keyword', 'search keyword', 'lookup keyword', 'grep exploit keyword', 'B'),
('cybersecurity', 'In Metasploit, which command runs the selected exploit against the target?', 'run', 'execute', 'exploit', 'Both A and C', 'D'),
('cybersecurity', 'What does `sqlmap -u "http://example.com?id=1" --dbs` do?', 'Dumps all tables from the database', 'Lists all available databases on the target', 'Runs a brute-force attack', 'Tests for XSS vulnerabilities', 'B'),
('cybersecurity', 'Which Burp Suite tool intercepts and modifies HTTP requests between the browser and server?', 'Scanner', 'Repeater', 'Proxy', 'Intruder', 'C'),
('cybersecurity', 'What does `hashcat -m 0 -a 0 hash.txt wordlist.txt` do?', 'Cracks MD5 hashes using a wordlist attack', 'Generates MD5 hashes from wordlist', 'Runs a brute-force on SHA-256 hashes', 'Verifies hashes against a known list', 'A'),
('cybersecurity', 'Which tool captures network packets on a live interface for analysis?', 'nmap', 'Metasploit', 'Wireshark', 'Burp Suite', 'C'),
('cybersecurity', 'What does `openssl genrsa -out key.pem 2048` generate?', 'A 2048-bit RSA public key', 'A 2048-bit RSA private key', 'A self-signed certificate', 'An AES-2048 encryption key', 'B'),
('cybersecurity', 'Which command generates a self-signed SSL certificate valid for 365 days using OpenSSL?', 'openssl create-cert -days 365', 'openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes', 'openssl cert -self-sign -days 365', 'openssl generate --cert --days 365', 'B'),
('cybersecurity', 'In Wireshark, which filter displays only HTTP traffic?', 'tcp.port == 80', 'http', 'filter http', 'protocol == http', 'B'),
('cybersecurity', 'What does the `john --wordlist=rockyou.txt hash.txt` command do?', 'Encrypts passwords using rockyou.txt', 'Cracks password hashes in hash.txt using the rockyou.txt wordlist', 'Generates hashes for words in rockyou.txt', 'Compares two hash files', 'B'),
('cybersecurity', 'Which OWASP Top 10 vulnerability occurs when user input is executed as SQL commands?', 'Cross-Site Scripting (XSS)', 'Broken Authentication', 'SQL Injection', 'Insecure Direct Object Reference', 'C'),
('cybersecurity', 'What does `ssh-keygen -t ed25519 -C "email@example.com"` do?', 'Generates an RSA SSH key pair', 'Generates an Ed25519 SSH key pair labeled with the email', 'Verifies an existing SSH key', 'Changes the SSH key passphrase', 'B'),
('cybersecurity', 'Which nmap flag saves scan output in all formats (normal, XML, grepable)?', '-oN', '-oX', '-oA', '-oG', 'C'),
('cybersecurity', 'In Metasploit, which command sets the target IP address for an exploit?', 'set TARGET 192.168.1.1', 'set RHOST 192.168.1.1', 'set IP 192.168.1.1', 'target set 192.168.1.1', 'B'),
('cybersecurity', 'What does a Cross-Site Request Forgery (CSRF) attack do?', 'Injects scripts into a web page', 'Tricks an authenticated user''s browser into making unwanted requests to a server', 'Intercepts network traffic', 'Exploits SQL queries', 'B'),
('cybersecurity', 'Which command in iptables blocks all incoming traffic on port 22?', 'iptables -A INPUT -p tcp --dport 22 -j REJECT', 'iptables -D INPUT -p tcp --dport 22', 'iptables -F INPUT port 22', 'iptables block --port 22', 'A'),
('cybersecurity', 'What does `nmap -p 1-65535 192.168.1.1` scan?', 'The top 1000 common ports', 'All 65535 TCP ports on the target', 'Ports 1 through 100', 'UDP ports only', 'B'),
('cybersecurity', 'Which Burp Suite tool is used to send a request repeatedly with modified parameters to test responses?', 'Proxy', 'Scanner', 'Repeater', 'Decoder', 'C'),
('cybersecurity', 'What is the purpose of a penetration test''s "scope" document?', 'Lists all found vulnerabilities', 'Defines which systems and actions are authorized during the test', 'Describes the tools used', 'Summarizes the test results', 'B'),
('cybersecurity', 'Which tool is used to perform DNS enumeration and zone transfers?', 'nmap', 'dig / host / dnsrecon', 'Burp Suite', 'Metasploit', 'B'),
('cybersecurity', 'What does `curl -I https://example.com` do?', 'Downloads the full page content', 'Sends a HEAD request and returns only HTTP response headers', 'Tests SSL certificate validity', 'Runs a port scan', 'B'),
('cybersecurity', 'In Metasploit, what is a "payload"?', 'The exploit code that finds the vulnerability', 'The code that runs on the target after exploitation (e.g., reverse shell)', 'The scan configuration', 'The post-exploitation module', 'B'),
('cybersecurity', 'Which command checks which ports are listening on a local Linux machine?', 'nmap localhost', 'netstat -tlnp', 'ps aux | grep port', 'ifconfig --ports', 'B'),
('cybersecurity', 'What does HTTPS use to encrypt web traffic?', 'SSH', 'TLS/SSL', 'IPSec', 'PGP', 'B'),
('cybersecurity', 'Which hashcat attack mode tries all character combinations up to a given length?', '-a 0 (dictionary)', '-a 1 (combinator)', '-a 3 (brute-force/mask)', '-a 6 (hybrid)', 'C'),
('cybersecurity', 'What does `nmap --script vuln 192.168.1.1` do?', 'Runs all NSE scripts against the target', 'Runs vulnerability detection scripts against the target', 'Lists known CVEs for the target OS', 'Scans for open ports only', 'B'),
('cybersecurity', 'Which type of XSS attack permanently stores the malicious script on the server?', 'Reflected XSS', 'DOM-based XSS', 'Stored (Persistent) XSS', 'Blind XSS', 'C'),
('cybersecurity', 'What is the purpose of a WAF (Web Application Firewall)?', 'Encrypts database traffic', 'Filters and monitors HTTP requests to block web attacks like SQLi and XSS', 'Manages SSL certificates', 'Performs DDoS mitigation at the network layer', 'B'),
('cybersecurity', 'Which Wireshark filter shows only traffic between two specific IPs?', 'ip.addr == 1.1.1.1 && ip.addr == 2.2.2.2', 'src == 1.1.1.1 and dst == 2.2.2.2', 'filter between 1.1.1.1 2.2.2.2', 'ip.filter(1.1.1.1, 2.2.2.2)', 'A'),
('cybersecurity', 'What does `gpg --encrypt --recipient user@example.com file.txt` do?', 'Signs the file with your private key', 'Encrypts file.txt using the recipient''s public GPG key', 'Decrypts file.txt for the recipient', 'Generates a GPG key pair', 'B'),
('cybersecurity', 'Which command tests if a web server is vulnerable to the Heartbleed bug?', 'nmap --script ssl-heartbleed', 'openssl test heartbleed', 'sqlmap --test heartbleed', 'curl --heartbleed', 'A'),
('cybersecurity', 'What does 2FA (Two-Factor Authentication) add to the login process?', 'A second password', 'A second authentication factor from a different category (e.g., password + OTP)', 'Biometric verification only', 'Email confirmation only', 'B'),
('cybersecurity', 'In the context of CTFs, what is steganography?', 'Breaking encryption algorithms', 'Hiding secret data inside ordinary files like images or audio', 'Fuzzing web applications', 'Reverse engineering binaries', 'B'),
('cybersecurity', 'Which command performs a UDP scan with nmap?', 'nmap -sT 192.168.1.1', 'nmap -sU 192.168.1.1', 'nmap -sV 192.168.1.1', 'nmap -sP 192.168.1.1', 'B'),
('cybersecurity', 'What is the role of a Certificate Authority (CA) in HTTPS?', 'Encrypts web traffic', 'Signs and validates SSL/TLS certificates to establish trust', 'Stores private keys', 'Manages DNS records', 'B'),
('cybersecurity', 'Which sqlmap flag dumps all data from a specific table?', '--dump --table users', '-T users --dump', '--extract table=users', '--table users --download', 'B'),
('cybersecurity', 'What does `chmod 600 ~/.ssh/id_rsa` do?', 'Makes the SSH key world-readable', 'Restricts the SSH private key to owner read/write only', 'Sets the key as executable', 'Removes all permissions from the key', 'B'),
('cybersecurity', 'Which attack involves overwhelming a server with traffic to make it unavailable?', 'Man-in-the-middle', 'SQL Injection', 'Distributed Denial of Service (DDoS)', 'Privilege escalation', 'C'),
('cybersecurity', 'In Burp Suite, what does the "Intruder" tool do?', 'Passively scans for vulnerabilities', 'Automates customized attacks by fuzzing parameters with payloads', 'Decodes encoded strings', 'Intercepts traffic', 'B'),
('cybersecurity', 'What does `nmap -A 192.168.1.1` enable?', 'Anonymous scanning mode', 'Aggressive scan: OS detection, version detection, script scanning, and traceroute', 'Scans all ports', 'Performs ARP scanning only', 'B'),
('cybersecurity', 'Which protocol does SSH use by default?', 'Port 21', 'Port 22', 'Port 23', 'Port 443', 'B'),
('cybersecurity', 'What is privilege escalation in cybersecurity?', 'Gaining access to a system for the first time', 'Gaining higher permissions than initially granted after initial access', 'Encrypting files to demand ransom', 'Scanning a network for vulnerabilities', 'B'),
('cybersecurity', 'Which tool is most commonly used for password spraying attacks?', 'nmap', 'Hydra or Medusa', 'Wireshark', 'Burp Suite', 'B'),
('cybersecurity', 'What does `openssl s_client -connect example.com:443` do?', 'Generates a CSR for the domain', 'Opens a raw TLS connection and shows the server''s SSL certificate details', 'Encrypts a file with the server''s key', 'Tests the server''s HTTP response', 'B'),

-- ============================================================
-- DOMAIN: devops (DevOps & CI/CD)
-- ============================================================
('devops', 'Which kubectl command rolls back a deployment to the previous revision?', 'kubectl revert deployment myapp', 'kubectl rollout undo deployment/myapp', 'kubectl rollback deployment myapp', 'kubectl deploy --undo myapp', 'B'),
('devops', 'Which kubectl command shows the logs of a running pod?', 'kubectl describe pod mypod --logs', 'kubectl get logs mypod', 'kubectl logs mypod', 'kubectl pod logs mypod', 'C'),
('devops', 'What does `kubectl apply -f deployment.yaml` do?', 'Validates the YAML file syntax', 'Creates or updates resources defined in the YAML file', 'Deletes the resources in the file', 'Restarts the deployment', 'B'),
('devops', 'Which kubectl command scales a deployment to 5 replicas?', 'kubectl scale deployment myapp --count=5', 'kubectl resize deployment myapp --replicas=5', 'kubectl scale deployment myapp --replicas=5', 'kubectl set replicas deployment/myapp 5', 'C'),
('devops', 'What does `docker build -t myapp:1.0 .` do?', 'Pulls the myapp:1.0 image from Docker Hub', 'Builds a Docker image tagged as myapp:1.0 from the current directory Dockerfile', 'Runs a container named myapp version 1.0', 'Creates a Docker volume', 'B'),
('devops', 'Which Docker command runs a container in detached mode and maps port 8080 to 80?', 'docker run myapp -d -p 8080:80', 'docker run -d -p 8080:80 myapp', 'docker start -p 8080:80 myapp', 'docker exec -d -p 8080:80 myapp', 'B'),
('devops', 'What does `docker-compose up -d` do?', 'Starts containers defined in docker-compose.yml in detached (background) mode', 'Downloads all images in docker-compose.yml', 'Stops all running containers', 'Builds images without starting containers', 'A'),
('devops', 'Which kubectl command deletes a pod named "mypod"?', 'kubectl remove pod mypod', 'kubectl delete pod mypod', 'kubectl kill pod mypod', 'kubectl stop pod mypod', 'B'),
('devops', 'In a GitHub Actions workflow, what does `on: push: branches: [main]` trigger?', 'The workflow runs whenever a PR is merged', 'The workflow runs on every push to the main branch', 'The workflow runs on every pull request', 'The workflow runs on a schedule', 'B'),
('devops', 'Which GitHub Actions keyword defines the commands to run in a step?', 'command', 'script', 'run', 'exec', 'C'),
('devops', 'What does `kubectl get pods -n kube-system` do?', 'Lists pods in the default namespace', 'Lists all pods in the kube-system namespace', 'Gets system resource usage', 'Shows Kubernetes system logs', 'B'),
('devops', 'Which Docker command shows all running containers?', 'docker list', 'docker ps', 'docker containers', 'docker status', 'B'),
('devops', 'What is the purpose of a Kubernetes ConfigMap?', 'Stores encrypted secrets', 'Stores non-sensitive configuration data as key-value pairs for pods to consume', 'Defines container resource limits', 'Manages service discovery', 'B'),
('devops', 'Which Helm command installs a chart named "nginx-ingress" from a repository?', 'helm add nginx-ingress', 'helm install nginx-ingress ingress-nginx/ingress-nginx', 'helm deploy nginx-ingress', 'helm run nginx-ingress', 'B'),
('devops', 'What does `docker exec -it mycontainer /bin/bash` do?', 'Starts a new container from the mycontainer image', 'Opens an interactive bash shell inside the running mycontainer container', 'Executes a one-time command and exits', 'Attaches to the container stdout', 'B'),
('devops', 'In GitHub Actions, how do you reference a secret named API_KEY in a workflow step?', '${{ secret.API_KEY }}', '${{ secrets.API_KEY }}', '$API_KEY', '${{ env.API_KEY }}', 'B'),
('devops', 'Which kubectl command shows details (events, conditions, resource limits) about a specific pod?', 'kubectl info pod mypod', 'kubectl get pod mypod --verbose', 'kubectl describe pod mypod', 'kubectl inspect pod mypod', 'C'),
('devops', 'What does `docker image prune -a` do?', 'Removes all stopped containers', 'Removes all unused Docker images, including those not referenced by any container', 'Removes dangling images only', 'Compresses all images', 'B'),
('devops', 'Which Kubernetes object exposes a set of pods as a network service?', 'Deployment', 'ConfigMap', 'Service', 'Ingress', 'C'),
('devops', 'What does `kubectl port-forward pod/mypod 8080:80` do?', 'Exposes the pod to the internet on port 8080', 'Forwards local port 8080 to port 80 on the pod', 'Creates a NodePort service', 'Updates the pod''s port configuration', 'B'),
('devops', 'In a Dockerfile, what does the `EXPOSE` instruction do?', 'Opens the specified port on the host machine', 'Documents which port the container listens on at runtime (does not publish it)', 'Allows external traffic on the port', 'Configures firewall rules', 'B'),
('devops', 'Which command initializes a new Helm chart?', 'helm new mychart', 'helm create mychart', 'helm init mychart', 'helm scaffold mychart', 'B'),
('devops', 'What does `kubectl get nodes` display?', 'All pods running in the cluster', 'All worker and control plane nodes in the cluster with their status', 'All services in the cluster', 'Available Kubernetes versions', 'B'),
('devops', 'In GitHub Actions, what does `needs: [build]` in a job definition do?', 'Requires the build job to fail before this job runs', 'Ensures this job runs only after the "build" job completes successfully', 'Imports artifacts from the build job', 'Sets the build job as optional', 'B'),
('devops', 'Which Docker instruction in a Dockerfile sets the working directory for subsequent commands?', 'CD /app', 'RUN cd /app', 'WORKDIR /app', 'DIR /app', 'C'),
('devops', 'What is the difference between a Kubernetes Deployment and a StatefulSet?', 'Deployments are faster than StatefulSets', 'StatefulSets provide stable network identities and persistent storage for stateful apps like databases', 'Deployments support more replicas than StatefulSets', 'There is no difference', 'B'),
('devops', 'Which command in Ansible runs a playbook?', 'ansible run playbook.yml', 'ansible-playbook playbook.yml', 'ansible play playbook.yml', 'ansible-run playbook.yml', 'B'),
('devops', 'What does `kubectl cordon mynode` do?', 'Deletes the node from the cluster', 'Marks the node as unschedulable so no new pods are scheduled on it', 'Drains all pods from the node', 'Restarts the node', 'B'),
('devops', 'In a Jenkins pipeline, what does the `stage` block define?', 'A parallel job', 'A logical phase of the pipeline (e.g., Build, Test, Deploy)', 'An agent configuration', 'An environment variable scope', 'B'),
('devops', 'Which `docker-compose` command stops and removes containers, networks, and volumes?', 'docker-compose stop', 'docker-compose rm', 'docker-compose down -v', 'docker-compose kill', 'C'),
('devops', 'What does a Kubernetes Ingress resource do?', 'Manages internal cluster DNS', 'Routes external HTTP/HTTPS traffic to services within the cluster based on rules', 'Provides persistent storage', 'Scales deployments automatically', 'B'),
('devops', 'Which kubectl command shows resource usage (CPU and memory) of all pods?', 'kubectl stats pods', 'kubectl get pods --metrics', 'kubectl top pods', 'kubectl describe pods --usage', 'C'),
('devops', 'In GitHub Actions, how do you cache dependencies between workflow runs?', 'Using the `store` action', 'Using the `actions/cache` action', 'Setting `persist: true` in the step', 'Using `cache: true` in the job definition', 'B'),
('devops', 'What does `kubectl drain mynode --ignore-daemonsets` do?', 'Stops all containers on the node', 'Safely evicts all pods from the node (except DaemonSet pods) before maintenance', 'Removes the node from the cluster permanently', 'Suspends the node', 'B'),
('devops', 'Which Docker command pushes an image to Docker Hub?', 'docker upload myrepo/myimage:tag', 'docker push myrepo/myimage:tag', 'docker publish myrepo/myimage:tag', 'docker deploy myrepo/myimage:tag', 'B'),
('devops', 'In a GitHub Actions matrix strategy, what does setting `fail-fast: false` do?', 'Prevents any jobs from failing', 'Allows all matrix jobs to complete even if one fails', 'Disables the matrix entirely', 'Makes the workflow fail immediately on any error', 'B'),
('devops', 'What is the purpose of `COPY` vs `ADD` in a Dockerfile?', 'They are identical', 'COPY is for simple file copy; ADD additionally supports URLs and tar extraction', 'ADD is for simple copy; COPY supports compression', 'COPY works for directories only; ADD for files only', 'B'),
('devops', 'Which Kubernetes resource automatically scales pods based on CPU usage?', 'ReplicaSet', 'StatefulSet', 'HorizontalPodAutoscaler (HPA)', 'DaemonSet', 'C'),
('devops', 'What does `kubectl config use-context my-cluster` do?', 'Creates a new cluster configuration', 'Switches kubectl to use the "my-cluster" context (cluster + credentials)', 'Updates cluster credentials', 'Connects to a remote cluster via SSH', 'B'),
('devops', 'Which GitHub Actions event triggers a workflow when a pull request is opened or updated?', 'on: pr', 'on: pull_request', 'on: merge_request', 'on: code_review', 'B'),

-- ============================================================
-- DOMAIN: data_science (Data Science, Analytics & Big Data)
-- ============================================================
('data_science', 'Which pandas method removes duplicate rows from a DataFrame?', 'df.remove_duplicates()', 'df.drop_duplicates()', 'df.deduplicate()', 'df.unique_rows()', 'B'),
('data_science', 'What does `df.fillna(0)` do in pandas?', 'Drops rows with NaN values', 'Fills all NaN values with 0', 'Replaces zeros with NaN', 'Counts NaN values per column', 'B'),
('data_science', 'Which pandas function reads a CSV file into a DataFrame?', 'pd.load_csv()', 'pd.open_csv()', 'pd.read_csv()', 'pd.import_csv()', 'C'),
('data_science', 'What does `df.groupby("category").agg({"sales": "sum"})` do?', 'Groups by category and counts rows', 'Groups by category and sums the sales column for each group', 'Filters rows where category equals sales', 'Creates a pivot table', 'B'),
('data_science', 'Which scikit-learn class splits data into training and test sets?', 'ModelSplitter()', 'DataSplit()', 'train_test_split()', 'TestTrainSplit()', 'C'),
('data_science', 'What does `model.fit(X_train, y_train)` do in scikit-learn?', 'Evaluates the model on training data', 'Trains the model on the provided features and labels', 'Predicts labels for training data', 'Scales the training features', 'B'),
('data_science', 'Which pandas method shows summary statistics (mean, std, min, max) for numeric columns?', 'df.summary()', 'df.stats()', 'df.describe()', 'df.info()', 'C'),
('data_science', 'What does `df.merge(df2, on="id", how="left")` do?', 'Inner joins df and df2 on the id column', 'Left joins df with df2 on the id column, keeping all rows from df', 'Concatenates df and df2 vertically', 'Merges only matching rows from both DataFrames', 'B'),
('data_science', 'Which scikit-learn metric calculates the proportion of correctly classified samples?', 'precision_score()', 'recall_score()', 'f1_score()', 'accuracy_score()', 'D'),
('data_science', 'What does `np.reshape(arr, (3, 4))` do?', 'Resizes the array and pads with zeros', 'Reshapes the array to 3 rows and 4 columns without changing data', 'Flattens the array', 'Creates a 3D array', 'B'),
('data_science', 'Which SQL clause filters rows after aggregation?', 'WHERE', 'HAVING', 'FILTER', 'GROUP BY', 'B'),
('data_science', 'What does a confusion matrix show in classification?', 'Feature importance scores', 'The counts of true positives, true negatives, false positives, and false negatives', 'The ROC curve data', 'Training loss per epoch', 'B'),
('data_science', 'Which pandas method returns the number of non-null values per column?', 'df.count()', 'df.non_null()', 'df.notnull().sum()', 'df.size()', 'A'),
('data_science', 'What does `StandardScaler().fit_transform(X)` do?', 'Normalizes X to [0, 1]', 'Standardizes X to have mean=0 and std=1', 'Encodes categorical variables', 'Removes outliers from X', 'B'),
('data_science', 'Which Python library provides the `DataFrame` and `Series` data structures?', 'numpy', 'scipy', 'pandas', 'matplotlib', 'C'),
('data_science', 'What does `df.pivot_table(values="sales", index="region", columns="quarter", aggfunc="sum")` produce?', 'A grouped bar chart', 'A pivot table showing total sales per region per quarter', 'A correlation matrix', 'A time series plot', 'B'),
('data_science', 'In scikit-learn, which method generates predictions from a trained model?', 'model.output()', 'model.run()', 'model.predict()', 'model.classify()', 'C'),
('data_science', 'Which SQL function returns the total number of rows in a result set?', 'SUM()', 'TOTAL()', 'COUNT()', 'ROWS()', 'C'),
('data_science', 'What does `df.dropna(subset=["col1", "col2"])` do?', 'Drops columns col1 and col2', 'Drops rows where col1 or col2 has a NaN value', 'Fills NaN values in col1 and col2 with 0', 'Drops all rows with any NaN', 'B'),
('data_science', 'Which Matplotlib function creates a scatter plot?', 'plt.bar()', 'plt.scatter()', 'plt.plot()', 'plt.hist()', 'B'),
('data_science', 'What does `cross_val_score(model, X, y, cv=5)` do in scikit-learn?', 'Trains 5 different models', 'Evaluates the model using 5-fold cross-validation and returns scores for each fold', 'Splits data into 5 train/test pairs and returns the best split', 'Performs hyperparameter tuning across 5 parameter sets', 'B'),
('data_science', 'Which pandas method converts a column to datetime format?', 'pd.to_datetime(df["col"])', 'df["col"].astype("datetime")', 'df["col"].to_date()', 'pd.parse_dates(df["col"])', 'A'),
('data_science', 'What does PCA (Principal Component Analysis) do?', 'Removes duplicate features', 'Reduces dimensionality by projecting data onto principal components that capture maximum variance', 'Classifies data into clusters', 'Normalizes feature scales', 'B'),
('data_science', 'Which SQL statement retrieves the top 5 highest-salary employees?', 'SELECT * FROM employees ORDER BY salary LIMIT 5', 'SELECT TOP 5 * FROM employees WHERE salary IS MAX', 'SELECT * FROM employees WHERE rank <= 5', 'SELECT FIRST 5 * FROM employees ORDER BY salary DESC', 'A'),
('data_science', 'In Seaborn, which function creates a heatmap of a correlation matrix?', 'sns.corrplot()', 'sns.heatmap(df.corr())', 'sns.matrix(df.corr())', 'sns.correlation(df)', 'B'),
('data_science', 'What does `GridSearchCV` do in scikit-learn?', 'Searches for the best training data split', 'Exhaustively searches over a parameter grid to find the best hyperparameters', 'Visualizes model performance as a grid', 'Runs cross-validation on a grid of models', 'B'),
('data_science', 'Which numpy function computes the dot product of two arrays?', 'np.multiply()', 'np.cross()', 'np.dot()', 'np.matmul() only', 'C'),
('data_science', 'What does `df["col"].value_counts()` return?', 'The mean and std of the column', 'A Series with unique values and their counts, sorted by frequency', 'The number of unique values', 'The cumulative count of values', 'B'),
('data_science', 'Which SQL join returns only rows where there is a match in both tables?', 'LEFT JOIN', 'FULL OUTER JOIN', 'INNER JOIN', 'CROSS JOIN', 'C'),
('data_science', 'What does `RandomForestClassifier(n_estimators=100)` create?', 'A single decision tree with 100 leaves', 'An ensemble of 100 decision trees that vote on classification', 'A neural network with 100 neurons', 'A boosted model with 100 weak learners', 'B'),
('data_science', 'Which pandas method applies a function to each element of a Series?', 'df.apply()', 'series.map()', 'series.applymap()', 'series.transform()', 'B'),
('data_science', 'What does `df.sort_values("sales", ascending=False)` do?', 'Sorts the DataFrame by index in descending order', 'Sorts rows by the "sales" column from highest to lowest', 'Filters rows with the highest sales', 'Ranks the sales column', 'B'),
('data_science', 'Which metric is most appropriate for evaluating a model on an imbalanced dataset?', 'Accuracy', 'F1-score or AUC-ROC', 'Mean Squared Error', 'R-squared', 'B'),
('data_science', 'What does `pd.concat([df1, df2], axis=0)` do?', 'Merges df1 and df2 on a common column', 'Stacks df1 and df2 vertically (row-wise)', 'Joins df1 and df2 side by side', 'Concatenates column names', 'B'),
('data_science', 'Which PySpark method loads a CSV file into a Spark DataFrame?', 'spark.load_csv()', 'spark.read.csv()', 'spark.read_csv()', 'SparkDF.from_csv()', 'B'),
('data_science', 'What does `LabelEncoder().fit_transform(y)` do?', 'One-hot encodes categorical labels', 'Converts categorical string labels to integer codes', 'Normalizes numeric labels to [0,1]', 'Removes duplicate labels', 'B'),
('data_science', 'Which SQL function calculates the average of a numeric column?', 'MEAN()', 'AVG()', 'AVERAGE()', 'SUM()/COUNT()', 'B'),
('data_science', 'What does `df.resample("M").sum()` do on a time-series DataFrame?', 'Resamples to milliseconds', 'Aggregates data by month and sums values within each month', 'Removes monthly outliers', 'Reindexes by month', 'B'),
('data_science', 'In scikit-learn, which class trains a gradient boosting model for classification?', 'GradientBooster()', 'XGBClassifier()', 'GradientBoostingClassifier()', 'BoostedTree()', 'C'),
('data_science', 'What does the `explained_variance_ratio_` attribute of a fitted PCA object return?', 'The number of principal components', 'The proportion of variance explained by each principal component', 'The total variance of the dataset', 'The eigenvalues of the covariance matrix', 'B'),
('data_science', 'Which pandas method writes a DataFrame to a CSV file?', 'df.save_csv()', 'df.export_csv()', 'df.to_csv()', 'df.write_csv()', 'C'),
('data_science', 'What does `np.where(condition, x, y)` return?', 'Indices where condition is True', 'An array with x where condition is True, y where False', 'A boolean mask', 'Filtered elements matching the condition', 'B'),
('data_science', 'Which SQL window function assigns a unique sequential rank to rows, with no gaps for ties?', 'RANK()', 'DENSE_RANK()', 'ROW_NUMBER()', 'NTILE()', 'B'),
('data_science', 'What does `train_test_split(X, y, test_size=0.2, random_state=42)` produce?', 'Splits data 80% train / 20% test with a fixed random seed for reproducibility', 'Splits data 20% train / 80% test', 'Applies cross-validation with 42 folds', 'Randomly samples 20% of features', 'A'),
('data_science', 'In PySpark, which method filters rows matching a condition?', 'df.query()', 'df.where() or df.filter()', 'df.select()', 'df.subset()', 'B'),
('data_science', 'What does `sns.boxplot(x="category", y="value", data=df)` visualize?', 'A scatter plot of category vs value', 'The distribution (median, quartiles, outliers) of value for each category', 'A bar chart of category counts', 'A line plot over time', 'B'),
('data_science', 'Which pandas operation selects rows where "age" is greater than 30?', 'df.query("age > 30") or df[df["age"] > 30]', 'df.filter("age", ">", 30)', 'df.where(df.age > 30)', 'df.select(age > 30)', 'A'),
('data_science', 'What does `Pipeline([("scaler", StandardScaler()), ("clf", LogisticRegression())])` do in scikit-learn?', 'Runs the scaler and classifier in parallel', 'Chains preprocessing (scaling) and model training into a single reusable object', 'Only scales data without training', 'Stacks two classifiers', 'B'),

-- Missing devops questions (10)
('devops', 'What does `kubectl rollout status deployment/myapp` show?', 'The deployment''s resource usage', 'The live rollout progress and whether the deployment completed successfully', 'The deployment''s YAML configuration', 'The number of scheduled pods', 'B'),
('devops', 'Which Docker command removes all stopped containers?', 'docker rm -all', 'docker prune containers', 'docker container prune', 'docker rm $(docker ps -a)', 'C'),
('devops', 'What is the difference between a Kubernetes Secret and a ConfigMap?', 'Secrets are larger than ConfigMaps', 'Secrets store sensitive data (encoded in base64); ConfigMaps store non-sensitive config data', 'ConfigMaps are encrypted at rest; Secrets are not', 'There is no difference', 'B'),
('devops', 'Which kubectl command lists all namespaces in a Kubernetes cluster?', 'kubectl list namespaces', 'kubectl show ns', 'kubectl get namespaces', 'kubectl describe namespaces', 'C'),
('devops', 'What does `docker inspect mycontainer` return?', 'Running logs from the container', 'Low-level JSON metadata about the container (network, mounts, config)', 'The container''s resource usage stats', 'The Dockerfile used to build the image', 'B'),
('devops', 'In GitHub Actions, what is an "artifact"?', 'A Docker image pushed to a registry', 'A file or directory produced by a workflow job that can be shared between jobs or downloaded', 'A cached dependency folder', 'A GitHub release asset', 'B'),
('devops', 'Which Terraform CLI command validates configuration files for syntax errors?', 'terraform lint', 'terraform check', 'terraform validate', 'terraform verify', 'C'),
('devops', 'What does `kubectl get events --sort-by=.lastTimestamp` show?', 'Pod logs sorted by time', 'Cluster events sorted by most recent last timestamp', 'Node resource events only', 'Deployment history', 'B'),
('devops', 'Which Docker flag sets environment variables when running a container?', '--env-file', '-v', '-e', '--config', 'C'),
('devops', 'What does `docker-compose logs -f myservice` do?', 'Shows only error logs for myservice', 'Streams live logs from the myservice container', 'Writes logs to a file', 'Restarts myservice and streams output', 'B'),

-- Missing cybersecurity questions (3)
('cybersecurity', 'Which tool is used to perform automated web application vulnerability scanning?', 'nmap', 'OWASP ZAP or Nikto', 'Metasploit', 'Wireshark', 'B'),
('cybersecurity', 'What does `tcpdump -i eth0 -w capture.pcap` do?', 'Reads packets from a file', 'Captures live network traffic on eth0 and writes it to a pcap file', 'Analyzes a saved pcap file', 'Filters traffic by protocol', 'B'),
('cybersecurity', 'In the context of web security, what is a "session token"?', 'An API key for server authentication', 'A temporary credential stored by the browser that identifies an authenticated user session', 'A JWT used for OAuth', 'A CSRF protection value', 'B'),

-- Missing cloud question (1)
('cloud', 'Which AWS CLI command describes available VPCs in your account?', 'aws vpc list', 'aws ec2 describe-vpcs', 'aws network list-vpcs', 'aws cloud describe-vpcs', 'B'),

-- Missing data_science questions (2)
('data_science', 'Which method in scikit-learn evaluates a regression model by computing the average squared difference between predicted and actual values?', 'mean_absolute_error()', 'r2_score()', 'mean_squared_error()', 'root_mean_error()', 'C'),
('data_science', 'What does `df.corr()` compute in pandas?', 'The covariance matrix of numeric columns', 'The pairwise Pearson correlation coefficients between numeric columns', 'The feature importance scores', 'The mutual information between columns', 'B');
