// Concatenates supabase/seeds/*.sql into supabase/seed.sql
// Run with: npm run seed:build

const fs = require('fs')
const path = require('path')

const DOMAIN_ORDER = ['ai', 'cloud', 'cybersecurity', 'devops', 'data_science']
const SEEDS_DIR = path.join(__dirname, '..', 'supabase', 'seeds')
const OUT_FILE = path.join(__dirname, '..', 'supabase', 'seed.sql')

const sections = DOMAIN_ORDER.map((domain) => {
  const file = path.join(SEEDS_DIR, `${domain}.sql`)
  if (!fs.existsSync(file)) throw new Error(`Missing seed file: ${file}`)
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n').trimEnd()
})

// Each section ends with trailing comma on last row — join sections with newline
// Then strip the very last trailing comma before the closing semicolon
const allRows = sections.join('\n\n') // blank line between domains
const withoutTrailingComma = allRows.replace(/,\s*$/, '')

const totalQuestions = sections.reduce((sum, s) => {
  return sum + (s.match(/^\s*\('/gm) || []).length
}, 0)

const header = [
  `-- Domain Knowledge Test Platform — Seed Data`,
  `-- ${totalQuestions} questions total. Generated by scripts/build-seed.js.`,
  `-- DO NOT edit seed.sql directly — edit supabase/seeds/<domain>.sql then run npm run seed:build`,
  ``,
  `TRUNCATE TABLE questions RESTART IDENTITY;`,
  ``,
  `INSERT INTO questions (domain, question, option_a, option_b, option_c, option_d, correct_answer) VALUES`,
  ``,
].join('\n')

const output = header + withoutTrailingComma + ';\n'

fs.writeFileSync(OUT_FILE, output, 'utf8')

console.log(`seed.sql written — ${totalQuestions} questions total`)
DOMAIN_ORDER.forEach((domain) => {
  const count = (sections[DOMAIN_ORDER.indexOf(domain)].match(/^\s*\('/gm) || []).length
  console.log(`  ${domain}: ${count}`)
})
